---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  
  labels:
    app: n8n
    component: service
spec:
  type: NodePort
  selector:
    app: n8n
    component: deployment
  ports:
  - protocol: TCP
    name: https
    port: 80
    targetPort: 5678
    nodePort: 30017
