---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  
  labels:
    app: n8n
    component: secrets
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "@#Yaali1363"
  # Basic auth credentials
  N8N_BASIC_AUTH_PASSWORD: "1363@#Yaali110"
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "hz"
