---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
   
  labels:
    app: n8n
    component: configmap
data:
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "Europe/lisbon"
  WEBHOOK_TUNNEL_URL: "https://n8n.dataanalyst.pt/" 
  # Database configurations
  DB_TYPE: "postgres"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  # Turn on basic auth
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
